name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dotnet tools
      run: dotnet tool restore

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2    
    - name: AWS Prerequisite Installation
      run: |
        sudo npm install -g aws-cdk@1.96.0
        cdk --version
        aws s3 ls              

    - name: Install build dependencies
      run: npm install

    - name: Build and bundle Lambda
      run: npm run build    

    - name: Deploy infrastructure and assets with CDK
      run: |
        cdk deploy --require-approval never
      
        
      